---
- include_tasks: setup.yml
  args:
    apply:
      become: yes
- include_tasks: initialize.yml
  args:
    apply:
      become: yes
- include_tasks: configure.yml
  args:
    apply:
      become: yes

- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_service_state }}"
    enabled: "{{ postgresql_service_enabled }}"
  become: yes

# Configure PostgreSQL.
- import_tasks: users.yml
- import_tasks: databases.yml
