---
- name: Create a jenkins job
  jenkins_job:
    config: "{{ lookup('template', 'templates/config.xml.j2') }}"
    name: do-final
    password: "{{ jenkins_admin_password }}"
    url: "http://{{ jenkins_hostname }}:8080"
    user: "{{ jenkins_admin_username }}"
