---
- name: Add elasticsearch mirror
  copy:
    src: elastic-7.x.list
    dest: "/etc/apt/sources.list.d/elastic-7.x.list"

- name: Install elasticsearch
  apt:
    name: elasticsearch
    state: present
    update_cache: yes

- name: Set ES service timeout
  lineinfile:
    path: /usr/lib/systemd/system/elasticsearch.service
    regexp: '^TimeoutStartSec='
    line: TimeoutStartSec=500
