---
- name: Deploy graylog config file
  template:
    src: server.conf.j2
    dest: /etc/graylog/server/server.conf
    mode: 0644
  notify: restart graylog

- name: Force Graylog restart
  meta: flush_handlers
