---
- name: Import Grafana signing key
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    state: present
    validate_certs: false

- name: Add Grafana repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    update_cache: yes

- name: Install Grafana
  apt:
    name: grafana=8.5.10
    update_cache: yes
  notify: restart grafana
