---
- name: Install dependencies.
  apt:
    name:
      - apt-transport-https
      - gnupg2
    update_cache: true
    state: present

- name: Add td-agent apt key.
  apt_key:
    url: https://packages.treasuredata.com/GPG-KEY-td-agent
    state: present

- name: Add td-agent repository.
  apt_repository:
    repo: deb https://packages.treasuredata.com/3/ubuntu/bionic bionic contrib
    state: present
    update_cache: true

- name: Install td-agent.
  package:
    name: td-agent
    state: present
