---
- name: restart grafana
  become: true
  service:
    daemon_reload: true
    name: grafana-server
    state: restarted
    enabled: yes

- name: reload grafana
  become: true
  service:
    name: grafana-server
    state: reloaded
